### PR TITLE
Feature: Contacts can have image assigned to them

### PR DESCRIPTION
**Pull request by mplekunov**
Created ImageAPI for handling image metadata in database, Server class for image handling on the server. Fixed bugs and updated endpoints.

### CODE REVIEW

**Comment by mplekunov** [comment]
Currently there is one known bug.

When you pass "incorrect" base64 string (during update operation), code should use previously cached image to restore it on the server and throw an error indicating unsuccessful save operation of the image on the server. 

What it does:
It saves previous image but doesn't throw an Error for some reason...

**Comment by mplekunov** [comment]
I'm still updating code, so don't merge it yet...

**Comment by mplekunov** [comment]
> Currently there is one known bug.
> 
> When you pass "incorrect" base64 string (during update operation), code should use previously cached image to restore it on the server and throw an error indicating unsuccessful save operation of the image on the server.
> 
> What it does: It saves previous image but doesn't throw an Error for some reason...

Fixed

**Review by nashirj — APPROVED** [review]
I didn't review thoroughly, but Michael tested this. We'll address any bugs that arise later.

**Pull request merged**
