### PR TITLE
Add authentication js

### PR DESCRIPTION
**Pull request by nashirj**
This can't be tested until the API login/register is done, but creating the PR because this should work. This doesn't need to be merged until the API stuff is merged.

It's mostly the code from class, with some modifications:
1) If a user is logged in, they'll be redirected to the main page; if they're not logged in they'll be redirected to the auth page.
2) Added registration capability
3) Added event listeners that submit the login/register form if user presses enter when in the password field

This PR partially addresses #5

### CODE REVIEW

**Comment by mplekunov** [comment]
One question. So, we are testing new password for min length, right? What about max length? Since we are hashing it using md5 in backend, we have to be sure that there is some max length, otherwise after hashing, it won't fit into the "Password" column in the database. @nashirj

**Comment by nashirj** [comment]
Yes, good point! I'll update this to include a max length check.

**Comment by nashirj** [comment]
actually, confusingly enough, it seems like the message length is arbitrary: https://stackoverflow.com/questions/3394503/maximum-length-for-md5-input-output

**Comment by nashirj** [comment]
Seems like md5 uses lossy encryption, so you can't recover the original password, but it's good enough for simply comparing hashes

**Comment by mplekunov** [comment]
> Seems like md5 uses lossy encryption, so you can't recover the original password, but it's good enough for simply comparing hashes

Alright, so it seems it's constant 32 digits. One problem less I guess 😄

**Pull request merged**
